-- CreateTable
CREATE TABLE "ROLES" (
    "ROLE_ID" SERIAL NOT NULL,
    "NAME" VARCHAR(50) NOT NULL,
    "DESCRIPTION" VARCHAR(255),
    "IS_ACTIVE" BOOLEAN NOT NULL DEFAULT true,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ROLES_pkey" PRIMARY KEY ("ROLE_ID")
);

-- CreateTable
CREATE TABLE "DEPARTMENTS" (
    "DEPT_ID" SERIAL NOT NULL,
    "DEPT_NAME" VARCHAR(200) NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "DEPARTMENTS_pkey" PRIMARY KEY ("DEPT_ID")
);

-- CreateTable
CREATE TABLE "RANKS" (
    "RANK_ID" SERIAL NOT NULL,
    "RANK_NAME" VARCHAR(100) NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RANKS_pkey" PRIMARY KEY ("RANK_ID")
);

-- CreateTable
CREATE TABLE "FLOORS" (
    "FLOOR_ID" SERIAL NOT NULL,
    "FLOOR_NAME" VARCHAR(100) NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "FLOORS_pkey" PRIMARY KEY ("FLOOR_ID")
);

-- CreateTable
CREATE TABLE "USERS" (
    "USER_ID" SERIAL NOT NULL,
    "USERNAME" VARCHAR(100) NOT NULL,
    "EMAIL" VARCHAR(255) NOT NULL,
    "PASSWORD" VARCHAR(255) NOT NULL,
    "ROLE_ID" INTEGER NOT NULL,
    "FULL_NAME" VARCHAR(200),
    "IS_ADMIN" BOOLEAN NOT NULL DEFAULT false,
    "PHONE" VARCHAR(20),
    "IS_ACTIVE" BOOLEAN NOT NULL DEFAULT true,
    "RANK_ID" INTEGER,
    "DEPT_ID" INTEGER,
    "FLOOR_ID" INTEGER,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "USERS_pkey" PRIMARY KEY ("USER_ID")
);

-- CreateTable
CREATE TABLE "ROLE_PERMISSIONS" (
    "ROLE_PERMISSIONS_ID" SERIAL NOT NULL,
    "ROLE_ID" INTEGER NOT NULL,
    "SUBJECT" VARCHAR(50) NOT NULL,
    "ACTION" VARCHAR(50) NOT NULL,
    "FIELD_NAME" VARCHAR(100),
    "CAN_ACCESS" BOOLEAN NOT NULL DEFAULT true,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ROLE_PERMISSIONS_pkey" PRIMARY KEY ("ROLE_PERMISSIONS_ID")
);

-- CreateTable
CREATE TABLE "MAIN_CATEGORIES" (
    "CAT_ID" SERIAL NOT NULL,
    "CAT_NAME" VARCHAR(200) NOT NULL,
    "DESCRIPTION" VARCHAR(500),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "MAIN_CATEGORIES_pkey" PRIMARY KEY ("CAT_ID")
);

-- CreateTable
CREATE TABLE "SUB_CATEGORIES" (
    "SUB_CAT_ID" SERIAL NOT NULL,
    "SUB_CAT_NAME" VARCHAR(200) NOT NULL,
    "CAT_ID" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(500),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SUB_CATEGORIES_pkey" PRIMARY KEY ("SUB_CAT_ID")
);

-- CreateTable
CREATE TABLE "ITEM_TYPES" (
    "ITEM_TYPE_ID" SERIAL NOT NULL,
    "ITEM_TYPE_NAME" VARCHAR(200) NOT NULL,
    "SUB_CAT_ID" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ITEM_TYPES_pkey" PRIMARY KEY ("ITEM_TYPE_ID")
);

-- CreateTable
CREATE TABLE "ITEMS" (
    "ITEM_ID" SERIAL NOT NULL,
    "ITEM_NAME" VARCHAR(300) NOT NULL,
    "SUB_CAT_ID" INTEGER,
    "ITEM_TYPE_ID" INTEGER,
    "LOCK_NUM" INTEGER,
    "SERIAL" VARCHAR(100),
    "KIND" VARCHAR(100),
    "SITUATION" VARCHAR(200),
    "PROPERTIES" VARCHAR(400),
    "HDD" VARCHAR(100),
    "RAM" VARCHAR(100),
    "IP" VARCHAR(50),
    "COMP_NAME" VARCHAR(200),
    "USER_ID" INTEGER,
    "DEPT_ID" INTEGER,
    "FLOOR_ID" INTEGER,
    "QUANTITY" INTEGER NOT NULL DEFAULT 0,
    "MIN_QUANTITY" INTEGER NOT NULL DEFAULT 0,
    "UNIT" VARCHAR(50) NOT NULL DEFAULT 'قطعة',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ITEMS_pkey" PRIMARY KEY ("ITEM_ID")
);

-- CreateTable
CREATE TABLE "MOVEMENT_TYPES" (
    "MOVEMENT_TYPE_ID" SERIAL NOT NULL,
    "TYPE_NAME" VARCHAR(100) NOT NULL,
    "TYPE_CODE" VARCHAR(20) NOT NULL,
    "EFFECT" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(500),
    "IS_ACTIVE" BOOLEAN NOT NULL DEFAULT true,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "MOVEMENT_TYPES_pkey" PRIMARY KEY ("MOVEMENT_TYPE_ID")
);

-- CreateTable
CREATE TABLE "INVENTORY_MOVEMENTS" (
    "MOVEMENT_ID" SERIAL NOT NULL,
    "ITEM_ID" INTEGER NOT NULL,
    "MOVEMENT_TYPE_ID" INTEGER NOT NULL,
    "QUANTITY" INTEGER NOT NULL,
    "PREVIOUS_QTY" INTEGER,
    "NEW_QTY" INTEGER,
    "MOVEMENT_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "USER_ID" INTEGER NOT NULL,
    "FROM_DEPT_ID" INTEGER,
    "TO_DEPT_ID" INTEGER,
    "FROM_FLOOR_ID" INTEGER,
    "TO_FLOOR_ID" INTEGER,
    "REFERENCE_NO" VARCHAR(100),
    "NOTES" VARCHAR(500),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "INVENTORY_MOVEMENTS_pkey" PRIMARY KEY ("MOVEMENT_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "ROLES_NAME_key" ON "ROLES"("NAME");

-- CreateIndex
CREATE UNIQUE INDEX "DEPARTMENTS_DEPT_NAME_key" ON "DEPARTMENTS"("DEPT_NAME");

-- CreateIndex
CREATE UNIQUE INDEX "RANKS_RANK_NAME_key" ON "RANKS"("RANK_NAME");

-- CreateIndex
CREATE UNIQUE INDEX "FLOORS_FLOOR_NAME_key" ON "FLOORS"("FLOOR_NAME");

-- CreateIndex
CREATE UNIQUE INDEX "USERS_USERNAME_key" ON "USERS"("USERNAME");

-- CreateIndex
CREATE UNIQUE INDEX "USERS_EMAIL_key" ON "USERS"("EMAIL");

-- CreateIndex
CREATE INDEX "USERS_ROLE_ID_idx" ON "USERS"("ROLE_ID");

-- CreateIndex
CREATE INDEX "USERS_RANK_ID_idx" ON "USERS"("RANK_ID");

-- CreateIndex
CREATE INDEX "USERS_DEPT_ID_idx" ON "USERS"("DEPT_ID");

-- CreateIndex
CREATE INDEX "USERS_FLOOR_ID_idx" ON "USERS"("FLOOR_ID");

-- CreateIndex
CREATE INDEX "USERS_EMAIL_idx" ON "USERS"("EMAIL");

-- CreateIndex
CREATE INDEX "USERS_IS_ACTIVE_idx" ON "USERS"("IS_ACTIVE");

-- CreateIndex
CREATE UNIQUE INDEX "ROLE_PERMISSIONS_ROLE_ID_SUBJECT_ACTION_FIELD_NAME_key" ON "ROLE_PERMISSIONS"("ROLE_ID", "SUBJECT", "ACTION", "FIELD_NAME");

-- CreateIndex
CREATE UNIQUE INDEX "MAIN_CATEGORIES_CAT_NAME_key" ON "MAIN_CATEGORIES"("CAT_NAME");

-- CreateIndex
CREATE INDEX "SUB_CATEGORIES_CAT_ID_idx" ON "SUB_CATEGORIES"("CAT_ID");

-- CreateIndex
CREATE UNIQUE INDEX "SUB_CATEGORIES_SUB_CAT_NAME_CAT_ID_key" ON "SUB_CATEGORIES"("SUB_CAT_NAME", "CAT_ID");

-- CreateIndex
CREATE UNIQUE INDEX "ITEM_TYPES_ITEM_TYPE_NAME_key" ON "ITEM_TYPES"("ITEM_TYPE_NAME");

-- CreateIndex
CREATE INDEX "ITEM_TYPES_SUB_CAT_ID_idx" ON "ITEM_TYPES"("SUB_CAT_ID");

-- CreateIndex
CREATE INDEX "ITEMS_SUB_CAT_ID_idx" ON "ITEMS"("SUB_CAT_ID");

-- CreateIndex
CREATE INDEX "ITEMS_ITEM_TYPE_ID_idx" ON "ITEMS"("ITEM_TYPE_ID");

-- CreateIndex
CREATE INDEX "ITEMS_USER_ID_idx" ON "ITEMS"("USER_ID");

-- CreateIndex
CREATE INDEX "ITEMS_DEPT_ID_idx" ON "ITEMS"("DEPT_ID");

-- CreateIndex
CREATE INDEX "ITEMS_FLOOR_ID_idx" ON "ITEMS"("FLOOR_ID");

-- CreateIndex
CREATE INDEX "ITEMS_SERIAL_idx" ON "ITEMS"("SERIAL");

-- CreateIndex
CREATE INDEX "ITEMS_IP_idx" ON "ITEMS"("IP");

-- CreateIndex
CREATE UNIQUE INDEX "MOVEMENT_TYPES_TYPE_NAME_key" ON "MOVEMENT_TYPES"("TYPE_NAME");

-- CreateIndex
CREATE UNIQUE INDEX "MOVEMENT_TYPES_TYPE_CODE_key" ON "MOVEMENT_TYPES"("TYPE_CODE");

-- CreateIndex
CREATE INDEX "INVENTORY_MOVEMENTS_ITEM_ID_idx" ON "INVENTORY_MOVEMENTS"("ITEM_ID");

-- CreateIndex
CREATE INDEX "INVENTORY_MOVEMENTS_MOVEMENT_DATE_idx" ON "INVENTORY_MOVEMENTS"("MOVEMENT_DATE");

-- CreateIndex
CREATE INDEX "INVENTORY_MOVEMENTS_MOVEMENT_TYPE_ID_idx" ON "INVENTORY_MOVEMENTS"("MOVEMENT_TYPE_ID");

-- CreateIndex
CREATE INDEX "INVENTORY_MOVEMENTS_USER_ID_idx" ON "INVENTORY_MOVEMENTS"("USER_ID");

-- AddForeignKey
ALTER TABLE "USERS" ADD CONSTRAINT "USERS_ROLE_ID_fkey" FOREIGN KEY ("ROLE_ID") REFERENCES "ROLES"("ROLE_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USERS" ADD CONSTRAINT "USERS_RANK_ID_fkey" FOREIGN KEY ("RANK_ID") REFERENCES "RANKS"("RANK_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USERS" ADD CONSTRAINT "USERS_DEPT_ID_fkey" FOREIGN KEY ("DEPT_ID") REFERENCES "DEPARTMENTS"("DEPT_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USERS" ADD CONSTRAINT "USERS_FLOOR_ID_fkey" FOREIGN KEY ("FLOOR_ID") REFERENCES "FLOORS"("FLOOR_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ROLE_PERMISSIONS" ADD CONSTRAINT "ROLE_PERMISSIONS_ROLE_ID_fkey" FOREIGN KEY ("ROLE_ID") REFERENCES "ROLES"("ROLE_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SUB_CATEGORIES" ADD CONSTRAINT "SUB_CATEGORIES_CAT_ID_fkey" FOREIGN KEY ("CAT_ID") REFERENCES "MAIN_CATEGORIES"("CAT_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ITEM_TYPES" ADD CONSTRAINT "ITEM_TYPES_SUB_CAT_ID_fkey" FOREIGN KEY ("SUB_CAT_ID") REFERENCES "SUB_CATEGORIES"("SUB_CAT_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ITEMS" ADD CONSTRAINT "ITEMS_SUB_CAT_ID_fkey" FOREIGN KEY ("SUB_CAT_ID") REFERENCES "SUB_CATEGORIES"("SUB_CAT_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ITEMS" ADD CONSTRAINT "ITEMS_ITEM_TYPE_ID_fkey" FOREIGN KEY ("ITEM_TYPE_ID") REFERENCES "ITEM_TYPES"("ITEM_TYPE_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ITEMS" ADD CONSTRAINT "ITEMS_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES "USERS"("USER_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ITEMS" ADD CONSTRAINT "ITEMS_DEPT_ID_fkey" FOREIGN KEY ("DEPT_ID") REFERENCES "DEPARTMENTS"("DEPT_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ITEMS" ADD CONSTRAINT "ITEMS_FLOOR_ID_fkey" FOREIGN KEY ("FLOOR_ID") REFERENCES "FLOORS"("FLOOR_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INVENTORY_MOVEMENTS" ADD CONSTRAINT "INVENTORY_MOVEMENTS_ITEM_ID_fkey" FOREIGN KEY ("ITEM_ID") REFERENCES "ITEMS"("ITEM_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INVENTORY_MOVEMENTS" ADD CONSTRAINT "INVENTORY_MOVEMENTS_MOVEMENT_TYPE_ID_fkey" FOREIGN KEY ("MOVEMENT_TYPE_ID") REFERENCES "MOVEMENT_TYPES"("MOVEMENT_TYPE_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INVENTORY_MOVEMENTS" ADD CONSTRAINT "INVENTORY_MOVEMENTS_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES "USERS"("USER_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INVENTORY_MOVEMENTS" ADD CONSTRAINT "INVENTORY_MOVEMENTS_FROM_DEPT_ID_fkey" FOREIGN KEY ("FROM_DEPT_ID") REFERENCES "DEPARTMENTS"("DEPT_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INVENTORY_MOVEMENTS" ADD CONSTRAINT "INVENTORY_MOVEMENTS_TO_DEPT_ID_fkey" FOREIGN KEY ("TO_DEPT_ID") REFERENCES "DEPARTMENTS"("DEPT_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INVENTORY_MOVEMENTS" ADD CONSTRAINT "INVENTORY_MOVEMENTS_FROM_FLOOR_ID_fkey" FOREIGN KEY ("FROM_FLOOR_ID") REFERENCES "FLOORS"("FLOOR_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INVENTORY_MOVEMENTS" ADD CONSTRAINT "INVENTORY_MOVEMENTS_TO_FLOOR_ID_fkey" FOREIGN KEY ("TO_FLOOR_ID") REFERENCES "FLOORS"("FLOOR_ID") ON DELETE SET NULL ON UPDATE CASCADE;
